# Generated by Django 3.0.8 on 2021-01-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preparation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Feedback',
            new_name='Answer',
        ),
    ]
