# Generated by Django 3.0.8 on 2021-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation', '0002_auto_20210107_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Branch',
            field=models.CharField(default='', max_length=10),
        ),
    ]
